### ISSUE TITLE
Set up issue

### ISSUE THREAD

**Issue by mycatnamedweb** [lsgunth/perftest#1]
Hi,
I'm trying to run a latency test for the first time but I get an error when I try to execute it.

My steps:
- Downloaded and unzipped the repo on the box on which I want to run the server for the test
- Executed:
  ./autogen
  ./configure
  make clean && make V=1
 ./ib_send_lat --duration=30 -H

  > Port number 1 state is Down
  >     Couldn't set the link layer
  >     Couldn't get context for the device
  > 

What am I doing wrong?

Running other tests using RDMA (eg. [the ones in Accelio](https://github.com/accelio/accelio/tree/fd3c54c907a3e5d5f218361e0a596930afe826e4/tests/usr/hello_test_lat)) the system shows no problems.

Thanks

**Comment by lsgunth** [comment]
Hey,

You should post to https://github.com/linux-rdma/perftest, this repo is a very old fork and I'm not responsible for it.

It's not really clear what the problem is. Do other tests in this suite work, like ib_read_bw? What about with the -R flag?

Logan

**Comment by mycatnamedweb** [comment]
Ok, I will. Thanks. PS. Actually there isn't an Issues section there.

I get the same outcome with the -R flag and running ib_read_bw

It's the first time that I use it so I may have to do some extra configuration steps?

**Comment by lsgunth** [comment]
I don't know anything about the accelio tests but it sure sounds like your RDMA setup is not working. I'd check to make sure tools like 'ibv_devinfo' and 'ibstatus' report the link is properly up.

**Comment by mycatnamedweb** [comment]
_ibv_devinfo_ and _ibstatus_ report that the link is properly up in fact other tests ran with another library work fine.
Must be a configuration issue somewhere..
Thanks anyway for your help : )

**Comment by mycatnamedweb** [comment]
( FYI I opened a stackoverflow and an issue on their GitHub: https://stackoverflow.com/questions/53179616/how-to-build-perftest-and-run-latency-tests-on-rdma )
